Container nvidia build =  85286409
out dir is .
fp16 activated!
python   run_squad.py --init_checkpoint=/data/bert_base/bert_base_uncased.pt --do_train --train_file=/data/squad/v1.1/train-v1.1.json --train_batch_size=384  --do_lower_case  --bert_model=bert-large-uncased  --learning_rate=0.0  --warmup_proportion=0.1 --seed=1  --num_train_epochs=2.0  --max_seq_length=384  --doc_stride=128  --output_dir=.  --vocab_file=/data/bert_base/bert-base-uncased-vocab.txt  --config_file=/data/bert_base/bert_config.json  --max_steps=100   --fp16  |& tee ./logfile.txt
device: cuda n_gpu: 1, distributed training: False, 16-bits training: True
DLL 2024-11-01 00:16:02.906015 - PARAMETER Config : ["Namespace(bert_model='bert-large-uncased', output_dir='.', init_checkpoint='/data/bert_base/bert_base_uncased.pt', train_file='/data/squad/v1.1/train-v1.1.json', predict_file=None, max_seq_length=384, doc_stride=128, max_query_length=64, do_train=True, do_predict=False, train_batch_size=384, predict_batch_size=8, learning_rate=0.0, num_train_epochs=2.0, max_steps=100.0, warmup_proportion=0.1, n_best_size=20, max_answer_length=30, verbose_logging=False, no_cuda=False, seed=1, gradient_accumulation_steps=1, do_lower_case=True, local_rank=-1, fp16=True, amp=False, loss_scale=0, version_2_with_negative=False, null_score_diff_threshold=0.0, vocab_file='/data/bert_base/bert-base-uncased-vocab.txt', config_file='/data/bert_base/bert_config.json', log_freq=50, json_summary='results/dllogger.json', eval_script='evaluate.py', do_eval=False, use_env=False, skip_checkpoint=False, disable_progress_bar=False, skip_cache=False, cache_dir=None)"] 
DLL 2024-11-01 00:16:02.906350 - PARAMETER SEED : 1 
WARNING: Output directory . already exists and is not empty. ['bind_pyt.py', 'processors', 'bert_configs', '.dockerignore', 'tokenization_utils.py', '.gitignore', 'modeling.py', 'data', 'configurations.yml', 'create_pretraining_data.py', 'NOTICE', 'inference.py', 'run_squad.py', 'file_utils.py', 'Dockerfile', 'logfile.txt', 'LICENSE', '__pycache__', 'triton', 'extract_features.py', 'schedulers.py', 'distillation', '.gitmodules', 'images', 'results', 'scripts', 'run_glue.py', 'utils.py', 'lamb_amp_opt', 'run_pretraining.py', 'run.sub', 'README.md', 'bind.sh', 'run_swag.py', 'tokenization.py', 'vocab', 'checkpoints', 'optimization.py', 'requirements.txt']
Traceback (most recent call last):
  File "/workspace/benchmark/LanguageModeling/BERT/run_squad.py", line 1199, in <module>
    main()
  File "/workspace/benchmark/LanguageModeling/BERT/run_squad.py", line 909, in main
    tokenizer = BertTokenizer(args.vocab_file, do_lower_case=args.do_lower_case, max_len=512) # for bert large
  File "/workspace/benchmark/LanguageModeling/BERT/tokenization.py", line 101, in __init__
    raise ValueError(
ValueError: Can't find a vocabulary file at path '/data/bert_base/bert-base-uncased-vocab.txt'. To load the vocabulary from a Google pretrained model use `tokenizer = BertTokenizer.from_pretrained(PRETRAINED_MODEL_NAME)`
[1c464adf3711:1520 :0:1520] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x190000ca7805a6)
==== backtrace (tid:   1520) ====
 0 0x000000000008dbf4 free()  ???:0
 1 0x000000000018d358 OPENSSL_LH_strhash()  ???:0
 2 0x000000000018de4c OPENSSL_LH_doall()  ???:0
 3 0x0000000000195bfc CRYPTO_new_ex_data()  ???:0
 4 0x000000000019abd8 CRYPTO_free_ex_data()  ???:0
 5 0x0000000000195edc OpenSSL_version()  ???:0
 6 0x000000000019e30c OPENSSL_cleanup()  ???:0
 7 0x000000000003cde8 secure_getenv()  ???:0
 8 0x000000000003cf0c exit()  ???:0
 9 0x0000000000027400 __libc_init_first()  ???:0
10 0x00000000000274cc __libc_start_main()  ???:0
11 0x00000000001da630 _start()  ???:0
=================================

real	0m1.746s
user	0m5.319s
sys	0m0.459s
DONE!
